version: "3.10.9"


services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  spark-master:
    image: bitnami/spark:3
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077

  spark-worker:
    image: bitnami/spark:3
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077

  news_summarization:
    image: news_summarization
    container_name: news_summarization
    build:
      context: ./domains/News_Summarization
      target: dev
    volumes:
      - ./domains/News_Summarization/:/src
    # env_file:
    #   - ./domains/news_summarization/.env
    #   - ./.env
    ports:
      - 3001:3000
    # depends_on:
    #   - ml_proxy
    restart: always
    networks:
      - uit-news-verification
    # un-comment this block to connect GPU to the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  news_classification:
    image: news_classification
    container_name: news_classification
    build:
      context: ./domains/News_Classification
      target: dev
    volumes:
      - ./domains/News_classification/:/src
    # env_file:
    #   - ./domains/news_classification/.env
    #   - ./.env
    ports:
      - 3002:3000
    # depends_on:
    #   - ml_proxy
    restart: always
    networks:
      - uit-news-verification
    # un-comment this block to connect GPU to the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  news_relevancy:
    image: news_relevancy
    container_name: news_relevancy
    build:
      context: ./domains/News_Relevancy
      target: dev
    volumes:
      - ./domains/News_Relevancy/:/src
    # env_file:
    #   - ./domains/news_relevancy/.env
    #   - ./.env
    ports:
      - 3003:3000
    # depends_on:
    #   - ml_proxy
    restart: always
    networks:
      - uit-news-verification
    # un-comment this block to connect GPU to the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  uit-news-verification:
    name: uit-news-verification